### PR TITLE
Added option to set cookies to webview when loading url

### PR DESCRIPTION
**Pull request by BWMuller**
Please note that the iOS code is untested

### CODE REVIEW

**Comment by Gericop** [comment]
When is this functionality going to be added?

**Comment by gedw99** [comment]
Its presumably tested only in the Simulator ?

**Comment by BWMuller** [comment]
@Gericop @gedw99 Its tested on android (Physical device)
Untested on iOS due to not having current access to a mac

**Comment by Gericop** [comment]
This solution is not really good as it only allows cookies to be set by name-value pairs, however, cookies can have more attributes, e.g. `Path`, `HttpOnly`, etc. Also, the cookie's URL is set by the opened URL which means if I open the site "https://example.com/something/" the cookie will only work for the `/something` path due to the missing `Path` attribute of the cookie. 

On iOS the attributes are explicitly set, for example `Path` is set to `/`, however, this also means that if the cookie you want to set has this value, it's gonna get overridden by the implementation.

**Comment by BWMuller** [comment]
Unable to get this working correctly in iOS, webview is not accepting the cookies at all.

**Comment by devraj-kumar** [comment]
how this works?

**Pull request closed without merging**
