### PR TITLE
Allow video players in Android WebView to maximize from Widget mode

### PR DESCRIPTION
**Pull request by mschneider**
Resolving #423 and possibly #279 (I only tested with a mp4 file)

### CODE REVIEW

**Comment by mschneider** [comment]
@charafau could you review this PR? Should I also create a patch for the main plugins repo?

**Comment by charafau** [comment]
@mschneider thanks for your PR ! For some reason I cannot see updates for repo in github and I'm busy with official webview.

Do you have any example where I can test that changes?

**Comment by mschneider** [comment]
Hi Rafal,

I replaced the target URL of the Webview from flutter.io with
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
 and built the example app for Android (&ios).

When opening the webview as a widget the previously grayed out fullscreen
button is now active and can be touched to trigger fullscreen playback. The
back button correctly closes the fullscreen view again.

Best,
Max

**Comment by charafau** [comment]
@mschneider  I needed to revert the changes because of bug I've found:

1. open the link with video
2. press fullscreen
3. click back (it comes back to normal view on webview)
4. click back again to close webview
5. it closes whole flutter app <--- should just go back to previous screen

**Comment by mschneider** [comment]
Confirmed, I started to look into it: seems like the back event is handled directly by flutter and not the native UI.

I'm currently working on a client's project that is not concerned by this issue. I'll have a look into at the earliest possible time (possibly only after the launch in early September)

**Comment by charafau** [comment]
got it. thanks!

**Comment by canewsin** [comment]
@mschneider any update ?

**Comment by mschneider** [comment]
no. forgot about it. not sure i'll look into this anytime soon

**Comment by jackhax** [comment]
@mschneider any update?

**Comment by canewsin** [comment]
@jackhax 

You can use this, based on latest stable.
```
  flutter_webview_plugin:
    git:
      url: https://github.com/canewsin/flutter_webview_plugin
      ref: fullscreen-support
```

**Comment by Sarthaktydy** [comment]
Is this working or any issues are there?

**Comment by rivetingpeppermint** [comment]
I tried @canewsin's fix and it does enable fullscreen, but I had to mash the fullscreen button many times before it opens. Tried with several Android devices, same behavior.

**Pull request merged**
