### PR TITLE
Add min sdk requirement and descriptions

### PR DESCRIPTION
**Pull request by lidongze91**
Currently flutter supports a minimum SDK version of 16 and all plugins should be able to match it, anything lower than that will probably cause some unwanted issues. We need to add those into Android Manifest and properly document it, same goes with the functions.

### CODE REVIEW

**Comment by charafau** [comment]
Thank you for PR! I don't think we should specify minSdk in library, android manifests are merged in the end, so if someone sets his minSdk to 16 it will be 16 afaik.

Currently there's no sdk limitation (beside androidX limit) so I don't think we could benefit from this change.

**Comment by mehmetf** [comment]
Android build system defaults your minSDK to 1 if you don't specify it. Gradle allows this but our internal BUILD system at Google throws warnings. 

It is OK for us to set this to minSDK 1 explicitly but that's also misleading and confusing given that Flutter itself does not support anything lower than 16. That's why we are proposing this change.

**Comment by lidongze91** [comment]
> Thank you for PR! I don't think we should specify minSdk in library, android manifests are merged in the end, so if someone sets his minSdk to 16 it will be 16 afaik.
> 
> Currently there's no sdk limitation (beside androidX limit) so I don't think we could benefit from this change.

If we don't specify it, we only supports min SDK version of 1 which is not ideal given that Flutter only supports 16+. Relying on other android manifest file merged together would not be reliable. Could you review please? Thanks.

**Comment by lidongze91** [comment]
Hi Rafal, would you do another review please?

**Comment by lidongze91** [comment]
@charafau Hi Rafal, could you do another review please?

**Comment by charafau** [comment]
merged thanks!

**Pull request merged**
