### PR TITLE
Add ignore ssl error parameter

### PR DESCRIPTION
**Pull request by jameshp**
This relates  to https://github.com/fluttercommunity/flutter_webview_plugin/issues/298 where in certain situations users have to ignore SSL certificates, e.g when working in test environments with self-signed certificates.  
The new optional flag _ignoreSSLErrors_ which defaults to false allows just that.

### CODE REVIEW

**Comment by geneho** [comment]
could anyone merge this please? Thanks!

**Comment by charafau** [comment]
Sorry was busy lately, will review today.

**Comment by charafau** [comment]
works like a charm, thank you !

**Comment by geneho** [comment]
thanks so much @charafau ! any idea when this would be pushed into pub as a new version ?

**Comment by jameshp** [comment]
thanks @charafau, glad to hear everything worked fine.  And thanks again for all the work you put into this package.

**Pull request merged**
